GROUP=com.afinsp
VERSION_NAME=0.1.0

POM_URL=https://github.com/afinsp/afinsp-clients
POM_SCM_URL=https://github.com/afinsp/afinsp-clients.git
POM_SCM_CONNECTION=scm:git:git@github.com:afinsp/afinsp-clients.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:afinsp/afinsp-clients.git
POM_LICENCE_NAME=The MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=afinsp
POM_DEVELOPER_NAME=Afinsp
POM_DEVELOPER_EMAIL=support@afinsp.com

POM_DESCRIPTION=Afinsp Billing SDK for Java
POM_NAME=afinsp
POM_ARTIFACT_ID=afinsp
POM_PACKAGING=jar
POM_ORGANIZATION_URL=https://afinsp.com

VENDOR_NAME=Afinsp (https://afinsp.com)
